### PR TITLE
major refactor of v5 to make creating options pages and fields more n…

### PR DESCRIPTION
**Pull request by scarstens**
major refactor of v5 to make creating options pages and fields more natural

### CODE REVIEW

**Comment by scarstens** [comment]
See and confirm usage with https://github.com/WordPress-Phoenix/wpop-example-panel/pull/2

**Comment by scarstens** [comment]
Screenshots for examples of each of the fields.
https://github.com/WordPress-Phoenix/wordpress-options-builder-class/issues/42

**Comment by mosrur** [comment]
Screenshots of each of the fields using WPOP Example Panel plugin on OneCMS - 

My_Sub_Level_Page_‹_Better_Homes_and_Gardens_—_WordPress_-_2019-07-29_16 25 00
My_Sub_Level_Page_‹_Better_Homes_and_Gardens_—_WordPress_-_2019-07-29_16 25 36
My_Sub_Level_Page_‹_Better_Homes_and_Gardens_—_WordPress_-_2019-07-29_16 25 47
My_Sub_Level_Page_‹_Better_Homes_and_Gardens_—_WordPress_-_2019-07-29_16 26 01
My_Sub_Level_Page_‹_Better_Homes_and_Gardens_—_WordPress_-_2019-07-29_16 26 12
Screen Shot 2019-07-29 at 4 27 51 PM

**Comment by scarstens** [comment]
LGTM

**Pull request merged**
